### PR TITLE
Test/add tests DelegateOnHost in submitTx

### PR DESCRIPTION
**Pull request by hoangdv2429**
Closes: #XXX

## Context and purpose of the change

TestDelegateOnHost_Successful
TestDelegateOnHost_ConnectionIDNotFound
TestDelegateOnHost_InvalidDelegationAccount
TestDelegationOnHost_ErrorGettingTargetDelegateAmtOnValidators

## Author's Checklist

I have...

- [ ] Run and PASSED locally all GAIA integration tests
- [ ] If the change is contentful, I either:
    - [ ] Added a new unit test OR 
    - [ ] Added test cases to existing unit tests
- [ ] OR this change is a trivial rework / code cleanup without any test coverage

If skipped any of the tests above, explain.

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] manually tested (if applicable)
- [ ] confirmed the author wrote unit tests for new logic
- [ ] reviewed documentation exists and is accurate

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes? 
  - [ ] Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?
  - [ ] This pull request updates existing proto field values (and require a backend and frontend migration)? 
  - [ ] Does this pull request change existing proto field names (and require a frontend migration)?
  How is the feature or change documented? 
      - [ ] not applicable
      - [ ] jira ticket `XXX` 
      - [ ] specification (`x/<module>/spec/`) 
      - [ ] README.md 
      - [ ] not documented

### CODE REVIEW

**Comment by ThanhNhann** [comment]
Hey @hoangdv2429, I see that you are missing some test cases for this function, plz update and ping me when it done

**Comment by hoangdv2429** [comment]
https://github.com/notional-labs/stride/blob/551bf6b44e7d4c170dfbc3c9d53c28c220107e75/x/stakeibc/keeper/msg_server_submit_tx.go#L37 I have worked on this before so this one will not fail unless owner is empty which it cannot because of this line https://github.com/notional-labs/stride/blob/551bf6b44e7d4c170dfbc3c9d53c28c220107e75/x/stakeibc/keeper/msg_server_submit_tx.go#L34. I believe that this line will belong to another test https://github.com/notional-labs/stride/blob/551bf6b44e7d4c170dfbc3c9d53c28c220107e75/x/stakeibc/keeper/msg_server_submit_tx.go#L91 because it's using SubmitTxsStrideEpoch ? https://github.com/notional-labs/stride/blob/551bf6b44e7d4c170dfbc3c9d53c28c220107e75/x/stakeibc/keeper/msg_server_submit_tx.go#L83 same as this line, because test for it have already been made. @ThanhNhann  Can you point out the things I should add to complete this ?

**Comment by ThanhNhann** [comment]
I total agree with you about the first case but the two cases remain I think it still should be implemented

**Comment by hoangdv2429** [comment]
> I total agree with you about the first case but the two cases remain I think it still should be implemented

Yes, then I will add test cases for those as well.

**Comment by hoangdv2429** [comment]
@ThanhNhann I have checked the remaining 2 cases. It seems that because all the params are scaffolded in side the function so it cannot fail. Can you check this as well

**Pull request closed without merging**
